[project]
name = "userapi2"
version = "0.1.0"
description = ""
authors = [
    {name = "xFlod",email = "densss306@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "logging (>=0.4.9.6,<0.5.0.0)",
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "sqlalchemy[asyncio] (>=2.0.52,<3.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
